name: Github Actions Demo
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello there"
      - run: echo "This job was triggered by ${{ github.event_name }}"
      - run: echo "The name of the branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List the files in the repository
        run: ls ${{ github.workspace }}
      - run: echo "The job status is ${{ job.status }} "